framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            test:
#                dsn: 'redis://localhost:6379/messages/symfony/consumer?auto_setup=true&serializer=1&stream_max_entries=0&dbindex=0'
                dsn: 'doctrine://default'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\UseCase\Test\Command': test

        buses:
            messenger.bus.test:
                middleware:
                    - App\UseCase\Test\Middleware