sylius_fixtures:
    suites:
        default:
            fixtures:
                product: ~
                user: ~
                review: ~
            listeners:
                review_purger: ~
                user_purger: ~
                product_purger: ~
