sylius_fixtures:
    suites:
        default:
            fixtures:
                product: ~
                user: ~
            listeners:
                product_purger: ~
                user_purger: ~